/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BreActionLog { 
    /**
     * The name of the action
     */
    readonly name?: string;
    /**
     * The runtime of the action in milliseconds
     */
    readonly runtime?: number;
    /**
     * The status of the action (ran, failed)
     */
    readonly status?: string;
}
