/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Behavior } from './behavior';
import { BundledSku } from './bundledSku';
import { Property } from './property';
import { Sku } from './sku';
import { StoreItem } from './storeItem';


export interface BundleItem extends StoreItem {
    /**
     * The skus of items to be included in this bundle, and how they influence the bundle total price.  Must have at least one SKU
     */
    bundledSkus: Array<BundledSku>;

}
export namespace BundleItem {
}
