/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Property } from './property';


export interface FileProperty extends Property {
    /**
     * A crc value for file integrity verification
     */
    crc?: string;

    /**
     * A description of the file
     */
    description?: string;

    /**
     * The type of file such as txt, mp3, mov or csv
     */
    fileType?: string;

    /**
     * The url of the file
     */
    url?: string;

}
