/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface MonitoringIncidentLevelResource {
    /**
     * The name of the level
     */
    name: string;

    /**
     * The current status of the level
     */
    status: MonitoringIncidentLevelResource.StatusEnum;

}
export namespace MonitoringIncidentLevelResource {
    export enum StatusEnum {
        OK = <any> 'OK',
        ALARM = <any> 'ALARM',
        INSUFFICIENTDATA = <any> 'INSUFFICIENT_DATA'
    }
}
