/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PropertyFieldResource { 
    /**
     * A description of the field
     */
    description?: string;
    /**
     * The type of values within a 'list' type field
     */
    innerType?: PropertyFieldResource.InnerTypeEnum;
    /**
     * A description of fields within objects within a 'list' type field, when inner_type is 'object'
     */
    innerTypeFields?: Array<PropertyFieldResource>;
    /**
     * The name of the field
     */
    name?: string;
    /**
     * Whether the field is required
     */
    required?: boolean;
    /**
     * The type of the field
     */
    type?: PropertyFieldResource.TypeEnum;
    /**
     * A list of valid values for 'enum' type fields
     */
    validValues?: Array<string>;
}
export namespace PropertyFieldResource {
    export type InnerTypeEnum = 'integer' | 'number' | 'bool' | 'string' | 'enumeration' | 'list' | 'object' | 'definition';
    export const InnerTypeEnum = {
        Integer: 'integer' as InnerTypeEnum,
        Number: 'number' as InnerTypeEnum,
        Bool: 'bool' as InnerTypeEnum,
        String: 'string' as InnerTypeEnum,
        Enumeration: 'enumeration' as InnerTypeEnum,
        List: 'list' as InnerTypeEnum,
        Object: 'object' as InnerTypeEnum,
        Definition: 'definition' as InnerTypeEnum
    };
    export type TypeEnum = 'integer' | 'number' | 'bool' | 'string' | 'enumeration' | 'list' | 'object' | 'definition';
    export const TypeEnum = {
        Integer: 'integer' as TypeEnum,
        Number: 'number' as TypeEnum,
        Bool: 'bool' as TypeEnum,
        String: 'string' as TypeEnum,
        Enumeration: 'enumeration' as TypeEnum,
        List: 'list' as TypeEnum,
        Object: 'object' as TypeEnum,
        Definition: 'definition' as TypeEnum
    };
}
