/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Schedule { 
    /**
     * The duration of the repeatable events
     */
    duration: number;
    /**
     * The unit of time for the duration field
     */
    durationUnit: Schedule.DurationUnitEnum;
    /**
     * How often the event is scheduled
     */
    repeat: Schedule.RepeatEnum;
}
export namespace Schedule {
    export type DurationUnitEnum = 'millisecond' | 'second' | 'minute' | 'hour' | 'day' | 'week' | 'month' | 'year';
    export const DurationUnitEnum = {
        Millisecond: 'millisecond' as DurationUnitEnum,
        Second: 'second' as DurationUnitEnum,
        Minute: 'minute' as DurationUnitEnum,
        Hour: 'hour' as DurationUnitEnum,
        Day: 'day' as DurationUnitEnum,
        Week: 'week' as DurationUnitEnum,
        Month: 'month' as DurationUnitEnum,
        Year: 'year' as DurationUnitEnum
    };
    export type RepeatEnum = 'DAILY' | 'WEEKLY';
    export const RepeatEnum = {
        DAILY: 'DAILY' as RepeatEnum,
        WEEKLY: 'WEEKLY' as RepeatEnum
    };
}
