/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface StripePaymentRequest {
    /**
     * The amount to pay, if not the full remaining balance (leave out to pay in full, but be careful no other partial payment has been started)
     */
    amount?: number;

    /**
     * The id of the invoice to pay
     */
    invoiceId: number;

    /**
     * A token from Stripe to identify payment info to be tied to the customer
     */
    token: string;

}
