/**
 * Knetik Platform API Documentation Latest
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SubscriptionResource {
    /**
     * A map of item additional properties, keyed on the property name. Must match the names and types defined in the template for this item type.
     */
    additionalProperties?: { [key: string]: models.Property; };

    /**
     * Who can purchase this subscription
     */
    availability?: SubscriptionResource.AvailabilityEnum;

    /**
     * A category for filtering items
     */
    category?: string;

    /**
     * The day of the month 1..31 this subscription will renew
     */
    consolidationDayOfMonth?: number;

    /**
     * The date the item was created, unix timestamp in seconds
     */
    createdDate?: number;

    /**
     * A list of country iso3 codes to include in the blacklist/whitelist geo policy
     */
    geoCountryList?: Array<string>;

    /**
     * Whether to use the geo_country_list as a black list or white list for item geographical availability
     */
    geoPolicyType?: SubscriptionResource.GeoPolicyTypeEnum;

    /**
     * The id of the item
     */
    id?: number;

    /**
     * A long description of the subscription
     */
    longDescription?: string;

    /**
     * The name of the item
     */
    name: string;

    /**
     * The billing options for this subscription
     */
    plans?: Array<models.SubscriptionPlanResource>;

    /**
     * A short description of the subscription.  Max 255 characters
     */
    shortDescription?: string;

    /**
     * A number to use in sorting items.  Default 500
     */
    sort?: number;

    /**
     * Used to schedule removal from store.  Null means the subscription will never be removed
     */
    storeEnd?: number;

    /**
     * Used to schedule appearance in store.  Null means the subscription will appear now
     */
    storeStart?: number;

    /**
     * List of tags used for filtering items
     */
    tags?: Array<string>;

    /**
     * An item template this item is validated against. May be null and no validation of additional properties will be done.
     */
    template?: string;

    /**
     * The unique key for the item
     */
    uniqueKey?: string;

    /**
     * The date the item was last updated
     */
    updatedDate?: number;

    /**
     * The vendor who provides the item
     */
    vendorId: number;

}
export namespace SubscriptionResource {
    export enum AvailabilityEnum {
        All = <any> 'all',
        NewSubscribers = <any> 'new_subscribers'
    }
    export enum GeoPolicyTypeEnum {
        Whitelist = <any> 'whitelist',
        Blacklist = <any> 'blacklist'
    }
}
