export * from './accessToken.service';
import { AccessTokenService } from './accessToken.service';
export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './amazonWebServicesS3.service';
import { AmazonWebServicesS3Service } from './amazonWebServicesS3.service';
export * from './authClients.service';
import { AuthClientsService } from './authClients.service';
export * from './authPermissions.service';
import { AuthPermissionsService } from './authPermissions.service';
export * from './authRoles.service';
import { AuthRolesService } from './authRoles.service';
export * from './authTokens.service';
import { AuthTokensService } from './authTokens.service';
export * from './campaigns.service';
import { CampaignsService } from './campaigns.service';
export * from './campaignsChallenges.service';
import { CampaignsChallengesService } from './campaignsChallenges.service';
export * from './campaignsRewards.service';
import { CampaignsRewardsService } from './campaignsRewards.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './configs.service';
import { ConfigsService } from './configs.service';
export * from './contentArticles.service';
import { ContentArticlesService } from './contentArticles.service';
export * from './contentComments.service';
import { ContentCommentsService } from './contentComments.service';
export * from './currencies.service';
import { CurrenciesService } from './currencies.service';
export * from './devices.service';
import { DevicesService } from './devices.service';
export * from './dispositions.service';
import { DispositionsService } from './dispositions.service';
export * from './fulfillment.service';
import { FulfillmentService } from './fulfillment.service';
export * from './gamificationAchievements.service';
import { GamificationAchievementsService } from './gamificationAchievements.service';
export * from './gamificationLeaderboards.service';
import { GamificationLeaderboardsService } from './gamificationLeaderboards.service';
export * from './gamificationLeveling.service';
import { GamificationLevelingService } from './gamificationLeveling.service';
export * from './gamificationMetrics.service';
import { GamificationMetricsService } from './gamificationMetrics.service';
export * from './gamificationTrivia.service';
import { GamificationTriviaService } from './gamificationTrivia.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './logs.service';
import { LogsService } from './logs.service';
export * from './mediaArtists.service';
import { MediaArtistsService } from './mediaArtists.service';
export * from './mediaModeration.service';
import { MediaModerationService } from './mediaModeration.service';
export * from './mediaPolls.service';
import { MediaPollsService } from './mediaPolls.service';
export * from './mediaVideos.service';
import { MediaVideosService } from './mediaVideos.service';
export * from './messaging.service';
import { MessagingService } from './messaging.service';
export * from './messagingTopics.service';
import { MessagingTopicsService } from './messagingTopics.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './objects.service';
import { ObjectsService } from './objects.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './paymentsApple.service';
import { PaymentsAppleService } from './paymentsApple.service';
export * from './paymentsFattMerchant.service';
import { PaymentsFattMerchantService } from './paymentsFattMerchant.service';
export * from './paymentsOptimal.service';
import { PaymentsOptimalService } from './paymentsOptimal.service';
export * from './paymentsPayPalClassic.service';
import { PaymentsPayPalClassicService } from './paymentsPayPalClassic.service';
export * from './paymentsStripe.service';
import { PaymentsStripeService } from './paymentsStripe.service';
export * from './paymentsTransactions.service';
import { PaymentsTransactionsService } from './paymentsTransactions.service';
export * from './paymentsWallets.service';
import { PaymentsWalletsService } from './paymentsWallets.service';
export * from './paymentsXsolla.service';
import { PaymentsXsollaService } from './paymentsXsolla.service';
export * from './reportingChallenges.service';
import { ReportingChallengesService } from './reportingChallenges.service';
export * from './reportingOrders.service';
import { ReportingOrdersService } from './reportingOrders.service';
export * from './reportingRevenue.service';
import { ReportingRevenueService } from './reportingRevenue.service';
export * from './reportingSubscriptions.service';
import { ReportingSubscriptionsService } from './reportingSubscriptions.service';
export * from './reportingUsage.service';
import { ReportingUsageService } from './reportingUsage.service';
export * from './reportingUsers.service';
import { ReportingUsersService } from './reportingUsers.service';
export * from './ruleEngineActions.service';
import { RuleEngineActionsService } from './ruleEngineActions.service';
export * from './ruleEngineEvents.service';
import { RuleEngineEventsService } from './ruleEngineEvents.service';
export * from './ruleEngineExpressions.service';
import { RuleEngineExpressionsService } from './ruleEngineExpressions.service';
export * from './ruleEngineGlobals.service';
import { RuleEngineGlobalsService } from './ruleEngineGlobals.service';
export * from './ruleEngineRules.service';
import { RuleEngineRulesService } from './ruleEngineRules.service';
export * from './ruleEngineTriggers.service';
import { RuleEngineTriggersService } from './ruleEngineTriggers.service';
export * from './ruleEngineVariables.service';
import { RuleEngineVariablesService } from './ruleEngineVariables.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './socialFacebook.service';
import { SocialFacebookService } from './socialFacebook.service';
export * from './socialGoogle.service';
import { SocialGoogleService } from './socialGoogle.service';
export * from './store.service';
import { StoreService } from './store.service';
export * from './storeBundles.service';
import { StoreBundlesService } from './storeBundles.service';
export * from './storeCoupons.service';
import { StoreCouponsService } from './storeCoupons.service';
export * from './storeSales.service';
import { StoreSalesService } from './storeSales.service';
export * from './storeShipping.service';
import { StoreShippingService } from './storeShipping.service';
export * from './storeShoppingCarts.service';
import { StoreShoppingCartsService } from './storeShoppingCarts.service';
export * from './storeSubscriptions.service';
import { StoreSubscriptionsService } from './storeSubscriptions.service';
export * from './storeVendors.service';
import { StoreVendorsService } from './storeVendors.service';
export * from './taxes.service';
import { TaxesService } from './taxes.service';
export * from './templatesProperties.service';
import { TemplatesPropertiesService } from './templatesProperties.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './usersAddresses.service';
import { UsersAddressesService } from './usersAddresses.service';
export * from './usersFriendships.service';
import { UsersFriendshipsService } from './usersFriendships.service';
export * from './usersGroups.service';
import { UsersGroupsService } from './usersGroups.service';
export * from './usersInventory.service';
import { UsersInventoryService } from './usersInventory.service';
export * from './usersRelationships.service';
import { UsersRelationshipsService } from './usersRelationships.service';
export * from './usersSubscriptions.service';
import { UsersSubscriptionsService } from './usersSubscriptions.service';
export * from './utilBatch.service';
import { UtilBatchService } from './utilBatch.service';
export * from './utilHealth.service';
import { UtilHealthService } from './utilHealth.service';
export * from './utilMaintenance.service';
import { UtilMaintenanceService } from './utilMaintenance.service';
export * from './utilSecurity.service';
import { UtilSecurityService } from './utilSecurity.service';
export * from './utilVersion.service';
import { UtilVersionService } from './utilVersion.service';
export const APIS = [AccessTokenService, ActivitiesService, AmazonWebServicesS3Service, AuthClientsService, AuthPermissionsService, AuthRolesService, AuthTokensService, CampaignsService, CampaignsChallengesService, CampaignsRewardsService, CategoriesService, ChatService, ConfigsService, ContentArticlesService, ContentCommentsService, CurrenciesService, DevicesService, DispositionsService, FulfillmentService, GamificationAchievementsService, GamificationLeaderboardsService, GamificationLevelingService, GamificationMetricsService, GamificationTriviaService, InvoicesService, LocationsService, LogsService, MediaArtistsService, MediaModerationService, MediaPollsService, MediaVideosService, MessagingService, MessagingTopicsService, NotificationsService, ObjectsService, PaymentsService, PaymentsAppleService, PaymentsFattMerchantService, PaymentsOptimalService, PaymentsPayPalClassicService, PaymentsStripeService, PaymentsTransactionsService, PaymentsWalletsService, PaymentsXsollaService, ReportingChallengesService, ReportingOrdersService, ReportingRevenueService, ReportingSubscriptionsService, ReportingUsageService, ReportingUsersService, RuleEngineActionsService, RuleEngineEventsService, RuleEngineExpressionsService, RuleEngineGlobalsService, RuleEngineRulesService, RuleEngineTriggersService, RuleEngineVariablesService, SearchService, SocialFacebookService, SocialGoogleService, StoreService, StoreBundlesService, StoreCouponsService, StoreSalesService, StoreShippingService, StoreShoppingCartsService, StoreSubscriptionsService, StoreVendorsService, TaxesService, TemplatesPropertiesService, UsersService, UsersAddressesService, UsersFriendshipsService, UsersGroupsService, UsersInventoryService, UsersRelationshipsService, UsersSubscriptionsService, UtilBatchService, UtilHealthService, UtilMaintenanceService, UtilSecurityService, UtilVersionService];
